pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs

// The emoji picker: the dataset, the frequently-used tally, and what happens
// when one is chosen.
//
// super+E used to open walker on elephant's `symbols` provider, which sorts by
// name -- so an empty query opened on "1st place medal", "abacus", "accordion",
// with the emoji nobody wants next to the ones everybody does and no shape to
// the list at all. Every emoji keyboard worth using, macOS's included, is in
// CLDR order under the standard headings instead, so this replaces the provider
// rather than trying to reorder it: elephant has no ordering knob, and walker's
// list is flat and cannot carry the headings.
//
// The `.` prefix in walker still reaches the symbols provider, which is where
// the arrows, the maths and the currency signs live -- none of which are emoji
// and none of which belong in this grid.
Singleton {
	id: root

	property bool panelOpen: false

	// [{ name, emoji: [{ c, n, k }] }], in the order the panel draws them.
	// Empty until the panel is first opened; see the loader below.
	property var categories: []

	// emoji -> { n: times chosen, t: last chosen, epoch ms }. The tally behind
	// "Frequently Used", and the one piece of this that outlives the session.
	property var usage: ({})

	// How many the "Frequently Used" section holds: two full rows of the grid.
	// Enough that the handful anyone actually reaches for is always there,
	// short enough that it stays a shortcut rather than a second picker.
	readonly property int frequentCount: 16

	// The tally resolved back into records, most-used first. Ties go to the
	// most recently used, so a burst of new emoji settles in a stable order
	// instead of shuffling on every open.
	readonly property var frequent: {
		if (categories.length === 0)
			return [];

		const byGlyph = {};
		for (const cat of categories)
			for (const e of cat.emoji)
				byGlyph[e.c] = e;

		return Object.keys(usage)
			.filter(c => byGlyph[c])
			.sort((a, b) => (usage[b].n - usage[a].n) || (usage[b].t - usage[a].t))
			.slice(0, frequentCount)
			.map(c => byGlyph[c]);
	}

	function toggle(): void {
		// The dataset is 1500-odd entries of JSON. Nothing outside the panel
		// reads it, so the first open is what pays for the parse rather than
		// every login; setting the path is what starts the load.
		if (data.path === "")
			data.path = `${Paths.dataDir}/emoji.json`;

		panelOpen = !panelOpen;
	}

	function close(): void {
		panelOpen = false;
	}

	// Chosen: onto the clipboard, into the window that had focus, and into the
	// tally. Closing first is not cosmetic -- the paste waits for this panel's
	// layer surface to go away before it types, because until then the panel
	// still holds the keyboard and ctrl+v would land in the search box.
	function pick(emoji: string): void {
		panelOpen = false;

		// A copy rather than a mutation in place: assigning the same object
		// back is not a change as far as QML is concerned -- it compares by
		// reference -- so `frequent` would go on showing the tally as it was
		// when the panel last opened.
		const next = Object.assign({}, usage);
		next[emoji] = {
			n: (usage[emoji]?.n ?? 0) + 1,
			t: Date.now()
		};
		usage = next;
		store.setText(JSON.stringify(next));

		paste.command = [`${Paths.home}/.config/scripts/copy-and-paste.sh`, "--layer", "quickshell:emoji", emoji];
		paste.running = true;
	}

	// The same script elephant runs for the clipboard and symbols providers --
	// the copy, then the wait for the picker's surface to vanish, then ctrl+v.
	// Shared rather than reimplemented here because the wait is the subtle part
	// and there is no reason for two versions of it to drift.
	Process {
		id: paste
	}

	// Generated by scripts/gen-emoji-data.py and checked in; see there for what
	// it is built from and why the order is what it is.
	FileView {
		id: data

		path: ""
		onLoaded: {
			try {
				root.categories = JSON.parse(text()).categories ?? [];
			} catch (e) {
				// A grid with nothing in it is a visible failure that says to
				// go and look at the file; a crash here would take the bar with
				// it.
				root.categories = [];
			}
		}
	}

	// Read blocking so the tally is in hand before the panel can be drawn:
	// loaded asynchronously, the first open of a session would show an empty
	// "Frequently Used" that filled in a frame later.
	FileView {
		id: store

		path: `${Paths.state}/quickshell/emoji-usage.json`
		blockLoading: true
		printErrors: false
		atomicWrites: true

		onLoaded: {
			try {
				root.usage = JSON.parse(text()) ?? ({});
			} catch (e) {
				// Unreadable means written by something that is not this; a
				// fresh tally costs nothing but the ordering of one session.
				root.usage = ({});
			}
		}
	}

	// FileView will not create the directory it writes into, and no singleton
	// here can rely on another having started first.
	Process {
		command: ["mkdir", "-p", `${Paths.state}/quickshell`]
		running: true
	}
}
